# Generated by Django 6.0.4 on 2026-04-25 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(db_index=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='DayPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('weekday_index', models.PositiveSmallIntegerField()),
                ('main_duration_minutes', models.PositiveIntegerField(default=0)),
                ('main_note', models.TextField(blank=True)),
                ('second_duration_minutes', models.PositiveIntegerField(default=0)),
                ('second_note', models.TextField(blank=True)),
                ('learning_duration_minutes', models.PositiveIntegerField(default=0)),
                ('learning_note', models.TextField(blank=True)),
                ('exercise_duration_minutes', models.PositiveIntegerField(default=0)),
                ('exercise_note', models.TextField(blank=True)),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='planner.week')),
            ],
            options={
                'ordering': ['date'],
                'constraints': [models.UniqueConstraint(fields=('week', 'date'), name='unique_day_per_week')],
            },
        ),
    ]
