# Generated by Django 6.0.4 on 2026-04-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayplan',
            name='exercise_goal',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dayplan',
            name='learning_goal',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dayplan',
            name='main_goal',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dayplan',
            name='second_goal',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='week',
            name='weekly_goal',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='week',
            name='weekly_note',
            field=models.TextField(blank=True),
        ),
    ]
