# Generated by Django 6.0.4 on 2026-08-16 19:22

from django.db import migrations, models


DEFAULT_PLANNER_SECTIONS = (
    ("slot_1", "Main", True, 1),
    ("slot_2", "Second", True, 2),
    ("slot_3", "Learning", True, 3),
    ("slot_4", "Exercise", True, 4),
    ("slot_5", "Section 5", False, 5),
    ("slot_6", "Section 6", False, 6),
    ("slot_7", "Section 7", False, 7),
    ("slot_8", "Section 8", False, 8),
    ("slot_9", "Section 9", False, 9),
    ("slot_10", "Section 10", False, 10),
)


def seed_planner_sections(apps, schema_editor):
    PlannerSectionConfig = apps.get_model("planner", "PlannerSectionConfig")
    PlannerSectionConfig.objects.bulk_create(
        [
            PlannerSectionConfig(
                slot_id=slot_id,
                label=label,
                active=active,
                position=position,
            )
            for slot_id, label, active, position in DEFAULT_PLANNER_SECTIONS
        ],
        ignore_conflicts=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_dayplan_exercise_goal_dayplan_learning_goal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannerSectionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_id', models.CharField(max_length=16, unique=True)),
                ('label', models.CharField(max_length=80)),
                ('active', models.BooleanField(default=False)),
                ('position', models.PositiveSmallIntegerField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='dayplan',
            name='slot_10_duration_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dayplan',
            name='slot_10_goal',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dayplan',
            name='slot_10_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dayplan',
            name='slot_5_duration_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dayplan',
            name='slot_5_goal',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dayplan',
            name='slot_5_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dayplan',
            name='slot_6_duration_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dayplan',
            name='slot_6_goal',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dayplan',
            name='slot_6_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dayplan',
            name='slot_7_duration_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dayplan',
            name='slot_7_goal',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dayplan',
            name='slot_7_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dayplan',
            name='slot_8_duration_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dayplan',
            name='slot_8_goal',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dayplan',
            name='slot_8_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dayplan',
            name='slot_9_duration_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dayplan',
            name='slot_9_goal',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dayplan',
            name='slot_9_note',
            field=models.TextField(blank=True),
        ),
        migrations.RunPython(seed_planner_sections, migrations.RunPython.noop),
    ]
