# Generated by Django 6.0.4 on 2026-08-25 19:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_plannersectionconfig_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayScheduleEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_minutes', models.PositiveSmallIntegerField()),
                ('end_minutes', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=160)),
                ('note', models.TextField(blank=True)),
                ('section_id', models.CharField(blank=True, max_length=16)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_entries', to='planner.dayplan')),
            ],
            options={
                'ordering': ['start_minutes', 'end_minutes', 'order', 'title'],
                'indexes': [models.Index(fields=['day', 'start_minutes'], name='planner_day_day_id_ade8c4_idx')],
            },
        ),
    ]
