# Generated by Django 6.0.4 on 2026-09-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0004_dayscheduleentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="dayplan",
            name="day_note",
            field=models.TextField(blank=True),
        ),
    ]
