# Generated by Django 6.0.4 on 2026-09-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0005_dayplan_day_note"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeekTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
                ("weekly_goal", models.TextField(blank=True)),
                ("weekly_note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["name"]},
        ),
    ]
