# Generated by Django 6.0.4 on 2026-09-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0006_weektemplate"),
    ]

    operations = [
        migrations.AddField(
            model_name="weektemplate",
            name="days",
            field=models.JSONField(default=list),
        ),
    ]
